workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Get Flutter packages
        script: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
          if [ -n "$PUBSPEC_PATH" ]; then
            cd $(dirname "$PUBSPEC_PATH")
          fi
          flutter packages pub get
      - name: Build APK
        script: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
          if [ -n "$PUBSPEC_PATH" ]; then
            cd $(dirname "$PUBSPEC_PATH")
          fi
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"
