org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.12.1

# Disattiva il controllo New DSL per impedire l'errore di AGP 9+
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
